### ISSUE TITLE
Roll Animation Broken

### ISSUE THREAD

**Issue by dqf318** [marmitoTH/FreedomEngine#2]
For some reason, when I reimported assets, the Roll animation broke, and no matter what I try, I can't seem to fix it.  Any help on that?

**Comment by marmitoTH** [comment]
Broken after reimporting? The roll animation is custom made inside Unity since the original one seems broken after extraction. You should try to download the roll animation again, if it doesn't work, you'll need to remade it.

**Comment by dqf318** [comment]
Decided to redownload and redo it, should work now.
